// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:tiny_weather/local/adapter/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BaseInfoAdapter());
    registerAdapter(BaseStateAdapter());
    registerAdapter(FlowAdapter());
    registerAdapter(PlanAdapter());
    registerAdapter(TodoAdapter());
  }
}
